### ISSUE TITLE
about data and reproduce results

### ISSUE THREAD

**Issue by bhralz** [olmozavala/Prostate_and_PZ_DL_Segmentation_Code#1]
Dear Olmo Zavala
Actually I cant found data in the provided link.
Please check that or send them in another way.
Thanks for your help.

**Comment by olmozavala** [comment]
Hello, sorry about that. At some point, I deleted the test data. It is being uploaded now. You just need to modify the MainConfig.py with your paths (wherever you download the test data) and everything should work just fine.
